postgresql:
  enabled: true
image:
  tag: "15.6.0"
auth:
  postgresPassword: postgres
  database: agent
  username: postgres
  password: postgres
volumePermissions:
  enabled: true
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

