image:
  registry: docker.io
  repository: library/postgres
  tag: "15.5"
  pullPolicy: IfNotPresent



auth:
  postgresPassword: postgres
  database: agent
  username: postgres
  password: postgres
  
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

