persistence:
  enabled: true

streamsets:
  tag: 3.53.1
  env:
    SDC_JAVA_OPTS: "-Xmx1024m -Xms1024m -server"
  containerPorts:
    - name: http
      containerPort: 18630
      protocol: TCP
  readinessProbe:
    httpGet:
      path: /
      port: 18630
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

podSecurityContext:
  fsGroup: 1000
