persistence:
  enabled: true

streamsets:
  tag: 3.53.1
  env:
    SDC_JAVA_OPTS: "-Xmx1024m -Xms1024m -server"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

podSecurityContext:
  fsGroup: 1000
